### ISSUE TITLE
피드백 받은 내용 적용

### ISSUE THREAD

**Issue by youngyoung0** [tell-me-team/Back-End#26]
## Description
---
api 피드백하면서 피드백 받으내용 수정

## Todo
---
- [x] 설문 답변 이후에 response 키워드, 설명, 유형
- [x] short url 디코드시 해당 유저의 설문에 몇 명이나 설문을 진행했는지 값 추가

## ETC
---
기타사항

**Comment by Jsim6342** [comment]
완료된 작업으로 파악되어 대신 Close 합니다.
